create table tmp_transacao (
   id SERIAL not null,
   data DATE,
   usuario INTEGER,
   cnpj VARCHAR(90) null,
   nomeFantasia VARCHAR(90) null,
   razaoSocial VARCHAR(90) null,
   adquirente VARCHAR(90) null,
   bandeira VARCHAR(90) null,
   operacao VARCHAR(90) null,
   afiliacao VARCHAR(90) null,
   autorizacao VARCHAR(90) null,
   documentoFiscal VARCHAR(90) null,
   referenciaLocal VARCHAR(90) null,
   numeroLogico VARCHAR(90) null,
   sequencial VARCHAR(90) null,
   terminal VARCHAR(90) null,
   plano INTEGER null,
   checkout VARCHAR(90) null,
   moeda VARCHAR(90) null,
   valor DECIMAL(12,2) null,
   uf VARCHAR(90) null,
   cidade VARCHAR(90) null,
   path VARCHAR(255) null,
   primary key(id)
)